<?xml version="1.0"?>
<package format="3">
  <name>parking_sim</name>
  <version>0.0.1</version>
  <description>Simple autonomous parking simulator for TurtleBot3 in ROS 2.</description>
  <maintainer email="user@example.com">student</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
